export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLEAR = "ALERT_CLEAR";

export const CLIENTS_GETALL_REQUEST = "CLIENTS_GETALL_REQUEST";
export const CLIENTS_GETALL_SUCCESS = "CLIENTS_GETALL_SUCCESS";
export const CLIENTS_GETALL_FAILURE = "CLIENTS_GETALL_FAILURE";
export const CLIENTS_INSERT_REQUEST = "CLIENTS_INSERT_REQUEST";
export const CLIENTS_INSERT_SUCCESS = "CLIENTS_INSERT_SUCCESS";
export const CLIENTS_INSERT_FAILURE = "CLIENTS_INSERT_FAILURE";
export const CLIENTS_UPDATE_REQUEST = "CLIENTS_UPDATE_REQUEST";
export const CLIENTS_UPDATE_SUCCESS = "CLIENTS_UPDATE_SUCCESS";
export const CLIENTS_UPDATE_FAILURE = "CLIENTS_UPDATE_FAILURE";
export const CLIENTS_DELETE_REQUEST = "CLIENTS_DELETE_REQUEST";
export const CLIENTS_DELETE_SUCCESS = "CLIENTS_DELETE_SUCCESS";
export const CLIENTS_DELETE_FAILURE = "CLIENTS_DELETE_FAILURE";

export const ITEMS_GETALL_REQUEST = "ITEMS_GETALL_REQUEST";
export const ITEMS_GETALL_SUCCESS = "ITEMS_GETALL_SUCCESS";
export const ITEMS_GETALL_FAILURE = "ITEMS_GETALL_FAILURE";
export const ITEM_GET_REQUEST = "ITEM_GET_REQUEST";
export const ITEM_GET_SUCCESS = "ITEM_GET_SUCCESS";
export const ITEM_GET_FAILURE = "ITEM_GET_FAILURE";
export const ITEMS_ADD_REQUEST = "ITEMS_ADD_REQUEST";
export const ITEMS_ADD_SUCCESS = "ITEMS_ADD_SUCCESS";
export const ITEMS_ADD_FAILURE = "ITEMS_ADD_FAILURE";
export const ITEMS_DELETE_REQUEST = "ITEMS_DELETE_REQUEST";
export const ITEMS_DELETE_SUCCESS = "ITEMS_DELETE_SUCCESS";
export const ITEMS_DELETE_FAILURE = "ITEMS_DELETE_FAILURE";
