export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLEAR = "ALERT_CLEAR";

export const CLIENTS_GETALL_REQUEST = "CLIENTS_GETALL_REQUEST";
export const CLIENTS_GETALL_SUCCESS = "CLIENTS_GETALL_SUCCESS";
export const CLIENTS_GETALL_FAILURE = "CLIENTS_GETALL_FAILURE";
